### ISSUE TITLE
Subscriber using TCP freezes

### ISSUE THREAD

**Issue by adamheinrich** [smcgill3/zeromq-matlab#5]
Thank you for the library!

I wanted to use it as a ZMQ subscriber using TCP (the publisher runs on a different box). Unfortunately, after calling 

```
s1 = zmq( 'subscribe', 'tcp', ip, port )
```

the program reported error ("Could not connect to socket!"). After calling it again, the program freezed and I had to restart Matlab.

After looking into zmq.cc I found that there is a little mistake at line 166. The line should be    

```
rc=zmq_connect( sockets[socket_cnt], zmq_channel );
```

instead of 

```
rc=zmq_bind( sockets[socket_cnt], zmq_channel );
```

After this fix the subscriber works as expected and Matlab code

```
s2 = zmq( 'subscribe', 'tcp', ip, port)
[recv_data,has_more] = zmq( 'receive', s2);
disp( char(recv_data') );
```

displays publisher's message correctly.

**Comment by smcgill3** [comment]
Thanks for the fix - I posted a commit here: https://github.com/smcgill3/zeromq-matlab/commit/74652c151864636b11f1767c9670c933f4272881
Let me know how this seems.
